### ISSUE TITLE
Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.

### ISSUE THREAD

**Issue by mattmorrisonsolidstudios** [umbraco/Umbraco.Courier.Contrib#27]
Hi Guys,

I am encountering an issue with v 1.0.21, let me know if you want me to fork and help sort this one out.
In the UI, the Courier process doesn't complete saying 'Ok' and the console reports a 500 error (attached).

![console error](https://cloud.githubusercontent.com/assets/21277373/24097669/cc9533ac-0d5e-11e7-945c-71ba1e3ff7e5.jpg)

In the logs there seems to be an issue with an invalid key as per subject; here's the log:

2017-03-20 11:06:54,108 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 131] Unloading (count: 0)
2017-03-20 11:06:54,155 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 131] Unloading (count: 0)
2017-03-20 11:06:55,171 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 33] Unloading (count: 0)
2017-03-20 11:06:58,655 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 110] Unloading (count: 0)
2017-03-20 11:06:58,671 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 110] Unloading (count: 0)
2017-03-20 11:06:58,671 [193] INFO  Umbraco.Courier.Core.TaskManager - [Thread 110] Added PackagingTask behind queue of : 0
2017-03-20 11:06:58,671 [193] INFO  Umbraco.Courier.Core.BackgroundTaskRunner - [Thread 110]  Task added Umbraco.Courier.Core.Tasks.PackagingTask
2017-03-20 11:06:58,671 [193] INFO  Umbraco.Courier.Core.TaskManager - [Thread 59] Starting PackagingTask with id: a408b8a8-6df2-4d67-9171-6eef68032a3c
2017-03-20 11:06:58,671 [193] DEBUG Umbraco.Courier.RepositoryProviders.Local - [Thread 59] Opening session: 99521188-ff70-4fad-a7ef-85c9fd045bbc
2017-03-20 11:06:58,671 [193] DEBUG Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider - [Thread 59] Opening session to ###MASKED URL###
2017-03-20 11:06:58,843 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:06:58,858 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:06:58,874 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:06:58,905 [193] DEBUG Umbraco.Courier.RepositoryProviders.Local - [Thread 2] Disposing: False
2017-03-20 11:06:58,905 [193] DEBUG Umbraco.Courier.RepositoryProviders.Local - [Thread 2] Disposing: False
2017-03-20 11:06:58,921 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:06:58,936 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:58,952 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:58,952 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:58,999 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,030 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,030 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,030 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,077 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'headerModules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,171 [193] WARN  Umbraco.Courier.Core.ResolutionManager - [Thread 59] Finished executing resolver: Document UK Delivery Property Data For provider: PropertyData (took 248ms)
2017-03-20 11:06:59,218 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:06:59,249 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:06:59,265 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:06:59,265 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:06:59,296 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,296 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,311 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,343 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,358 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,374 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,374 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,405 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'headerModules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:06:59,499 [193] WARN  Umbraco.Courier.Core.ResolutionManager - [Thread 59] Finished executing resolver: Document UK Delivery Property Data For provider: PropertyData (took 221ms)
2017-03-20 11:07:00,436 [193] INFO  Umbraco.Courier.Core.Packaging.RevisionPackaging - [Thread 59] Documents: c6f4ae41-3147-45f1-95e4-6f45f6056133 hash-mismatch (local/remote) c3f563f239ff08e9b1a0734277b325615dc83268ddf34329e21eb8499443f773 / 6e3514721e3095a2f7b98a146e89a0b746b6b9316b056d59189c0a8b02b8a241
2017-03-20 11:07:00,874 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:07:00,890 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:07:00,890 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:07:00,905 [193] ERROR Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver - [Thread 59] Error reading grid cell value: 
System.ArgumentException: Accessed JArray values with invalid key value: "dtgeContentTypeAlias". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Umbraco.Courier.Contrib.Resolvers.GridCellDataResolvers.DocTypeGridEditorGridCellResolver.ShouldRun(String view, GridValueControlModel cell)
2017-03-20 11:07:00,936 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:07:00,936 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:07:00,936 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:07:00,968 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:07:00,999 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:07:00,999 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:07:00,999 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'modules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:07:01,046 [193] DEBUG Umbraco.Courier.DataResolvers.PropertyDataResolvers.RTEImages - [Thread 59] No images found in RTE data for property 'headerModules' on 'c6f4ae41-3147-45f1-95e4-6f45f6056133'
2017-03-20 11:07:01,124 [193] WARN  Umbraco.Courier.Core.ResolutionManager - [Thread 59] Finished executing resolver: Document UK Delivery Property Data For provider: PropertyData (took 213ms)
2017-03-20 11:07:01,186 [193] INFO  Umbraco.Courier.Core.Packaging.RevisionPackaging - [Thread 59] PropertyData: c6f4ae41-3147-45f1-95e4-6f45f6056133 hash-mismatch (local/remote) 5dc83268ddf34329e21eb8499443f773 / 46b6b9316b056d59189c0a8b02b8a241
2017-03-20 11:07:01,499 [193] DEBUG Umbraco.Courier.RepositoryProviders.Local - [Thread 59] Disposing: True
2017-03-20 11:07:01,499 [193] DEBUG Umbraco.Courier.RepositoryProviders.Local - [Thread 59] Closing session: 99521188-ff70-4fad-a7ef-85c9fd045bbc
2017-03-20 11:07:01,499 [193] DEBUG Umbraco.Courier.Persistence.V6.NHibernate.NHibernateProvider - [Thread 59] Closing session, UseGlobalSession: False, key: 99521188-ff70-4fad-a7ef-85c9fd045bbc
2017-03-20 11:07:01,499 [193] DEBUG Umbraco.Courier.Persistence.V6.NHibernate.NHibernateGlobalSessionManager - [Thread 59] Closing session, IsInWebContext: False
2017-03-20 11:07:01,499 [193] DEBUG Umbraco.Courier.RepositoryProviders.Local - [Thread 59] Disposing: True
2017-03-20 11:07:01,499 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 59] Unloading (count: 0)
2017-03-20 11:07:01,499 [193] INFO  Umbraco.Courier.Core.TaskManager - [Thread 59] Completed PackagingTask with id: a408b8a8-6df2-4d67-9171-6eef68032a3c
2017-03-20 11:07:01,874 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 49] Unloading (count: 0)
2017-03-20 11:07:01,905 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 49] Unloading (count: 0)
2017-03-20 11:07:01,905 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 49] Unloading (count: 0)
2017-03-20 11:07:01,921 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 33] Unloading (count: 0)
2017-03-20 11:07:01,936 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 79] Unloading (count: 0)
2017-03-20 11:07:01,936 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 116] Unloading (count: 0)
2017-03-20 11:07:01,952 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 111] Unloading (count: 0)
2017-03-20 11:07:04,390 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 33] Unloading (count: 0)
2017-03-20 11:07:04,421 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 33] Unloading (count: 0)
2017-03-20 11:07:04,421 [193] INFO  Umbraco.Courier.Core.TaskManager - [Thread 33] Added ExtractionTask behind queue of : 0
2017-03-20 11:07:04,421 [193] INFO  Umbraco.Courier.Core.BackgroundTaskRunner - [Thread 33]  Task added Umbraco.Courier.Core.Tasks.ExtractionTask
2017-03-20 11:07:04,421 [193] INFO  Umbraco.Courier.Core.TaskManager - [Thread 81] Starting ExtractionTask with id: ca40f139-57d5-4d6f-912a-d4b1cfc0308f
2017-03-20 11:07:04,421 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Running PopulateGraph
2017-03-20 11:07:04,436 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Finished PopulateGraph (took 4ms)
2017-03-20 11:07:04,436 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 81] Adding event DeleteContentAndMedia To Queue: DeploymentComplete for session: eb6a7598-84e4-40cd-99ea-37287fc66d00
2017-03-20 11:07:04,436 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Starting extraction
2017-03-20 11:07:04,436 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Opens database session
2017-03-20 11:07:04,436 [193] DEBUG Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider - [Thread 81] Opening session to ###MASKED URL###
2017-03-20 11:07:04,436 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Transfering pre-extraction files
2017-03-20 11:07:04,436 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Running ExtractReadyRevisionBatch
2017-03-20 11:07:04,436 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Extracting batch of 2 items
2017-03-20 11:07:04,436 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Extracting: Sliding Table Column Width - Umbraco.Courier.Core.DependencyGraph+GraphNode
2017-03-20 11:07:04,468 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Extracting: UK Delivery - Umbraco.Courier.Core.DependencyGraph+GraphNode
2017-03-20 11:07:04,499 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Extracting batch of 1 items
2017-03-20 11:07:04,499 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Extracting: Document UK Delivery Property Data - Umbraco.Courier.Core.DependencyGraph+GraphNode
2017-03-20 11:07:34,593 [193] WARN  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Finished ExtractItem (took 30100ms)
2017-03-20 11:07:34,593 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Finished ExtractReadyRevisionBatch (took 30154ms)
2017-03-20 11:07:34,593 [193] ERROR Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] There was a problem with extracting database information for the item: Name:Document UK Delivery Property Data | Id:c6f4ae41-3147-45f1-95e4-6f45f6056133 | Provider:PropertyData
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> Exception has been thrown by the target of an invocation. ---> Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.  This failure occured while attempting to connect to the Principle server. ---> The wait operation timed out
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at Umbraco.Courier.RepositoryProviders.WebServiceProvider.RepositoryWebservice.Extract(String sessionKey, Byte[] item, ItemIdentifier itemId, Boolean overwrite, String user, String pass)
   at Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider.ExtractItem(Item item, Boolean overwrite)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractItem(GraphNode node, Boolean isDependency)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractReadyRevisionBatch()
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractReadyRevisionBatch()
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.Extract()
2017-03-20 11:07:34,593 [193] INFO  Umbraco.Courier.Core.Extraction.RevisionExtraction - [Thread 81] Rolling back changes due to errors
2017-03-20 11:07:34,608 [193] DEBUG Umbraco.Courier.RepositoryProviders.Local - [Thread 81] Disposing: True
2017-03-20 11:07:34,608 [193] WARN  Umbraco.Courier.RepositoryProviders.Local - [Thread 81] Closing session called but there is no session open: eb6a7598-84e4-40cd-99ea-37287fc66d00
2017-03-20 11:07:34,624 [193] DEBUG Umbraco.Courier.Core.EventManager - [Thread 81] Unloading (count: 1)
2017-03-20 11:07:34,624 [193] ERROR Umbraco.Courier.Core.TaskManager - [Thread 81] Error ExtractionTask with id: ca40f139-57d5-4d6f-912a-d4b1cfc0308f
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> Exception has been thrown by the target of an invocation. ---> Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.  This failure occured while attempting to connect to the Principle server. ---> The wait operation timed out
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at Umbraco.Courier.RepositoryProviders.WebServiceProvider.RepositoryWebservice.Extract(String sessionKey, Byte[] item, ItemIdentifier itemId, Boolean overwrite, String user, String pass)
   at Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider.ExtractItem(Item item, Boolean overwrite)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractItem(GraphNode node, Boolean isDependency)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractReadyRevisionBatch()
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractReadyRevisionBatch()
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.Extract()
   at Umbraco.Courier.Core.Tasks.ExtractionTask.Run()
   at Umbraco.Courier.Core.BackgroundTaskRunner`1.ConsumeTaskInternal(T task)
2017-03-20 11:07:34,624 [193] ERROR Umbraco.Courier.Core.BackgroundTaskRunner - [Thread 81] An error occurred consuming task
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> Exception has been thrown by the target of an invocation. ---> Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.  This failure occured while attempting to connect to the Principle server. ---> The wait operation timed out
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at Umbraco.Courier.RepositoryProviders.WebServiceProvider.RepositoryWebservice.Extract(String sessionKey, Byte[] item, ItemIdentifier itemId, Boolean overwrite, String user, String pass)
   at Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider.ExtractItem(Item item, Boolean overwrite)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractItem(GraphNode node, Boolean isDependency)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractReadyRevisionBatch()
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractReadyRevisionBatch()
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.Extract()
   at Umbraco.Courier.Core.Tasks.ExtractionTask.Run()
   at Umbraco.Courier.Core.BackgroundTaskRunner`1.ConsumeTaskInternal(T task)
2017-03-20 11:07:35,405 [193] DEBUG Umbraco.Courier.RepositoryProviders.Local - [Thread 2] Disposing: False

**Comment by jfsaliba** [comment]
I noticed those numerous debug messages about dtgeContentTypeAlias in the Courier logs too, but since I don't use dtge I just compiled the solution without that resolver. Hopefully someone who uses dtge can weigh in on the issue?

**Comment by leekelleher** [comment]
I think it's up to us (the community) to attempt to fix it.

@mattmorrisonsolidstudios @jfsaliba  I'm not sure which line number it happens on, I'm guessing this one? [`DocTypeGridEditorGridCellResolver.cs#L30`](https://github.com/umbraco/Umbraco.Courier.Contrib/blob/dev/src/Umbraco.Courier.Contrib.Resolvers/GridCellDataResolvers/DocTypeGridEditorGridCellResolver.cs#L30)

**Comment by mattmorrisonsolidstudios** [comment]
@leekelleher agreed, I'll check it out and see what I can do, I haven't got time this minute but I'm going to try and jump on this by the end of the week if no one else beats me to it.

**Comment by clausjensen** [comment]
I've merged in the fix - thanks a lot guys 😄
