### ISSUE TITLE
Umbraco courier failed for role based access node configured nodes

### ISSUE THREAD

**Issue by pyajamanam** [umbraco/Umbraco.Courier.Contrib#41]
Hi I have a node which is configured with role based access with roles allowed.if user login verified the role if not in role redirect to unauthorized page.

now i have configured the node when i remove public access it will deploy but it fails when configured in role based access.
error is 
```
"Message":"System.Web.Services.Protocols.SoapException: Server was unable to process request. ---\u003e Umbraco.Courier.Core.Exceptions.RetrieveException: Error retrieving item [DEALER] from provider [4715aa16-fa35-426f-bb67-674043557875]. ---\u003e System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).   
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
   at System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult\u0026 result)
   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult\u0026 result)\n   at System.Guid..ctor(String g)
   at Umbraco.Courier.Persistence.V6.NHibernate.Persisters.MemberGroupItem.RetrieveItem(ItemIdentifier itemId)
   at Umbraco.Courier.Core.ItemCrud`1.RetrieveItem[T1](ItemIdentifier itemId)
   at Umbraco.Courier.Core.ItemCrudProvider.RetrieveItem[T](ItemIdentifier itemId)
   --- End of inner exception stack trace ---
   at Umbraco.Courier.Core.ItemCrudProvider.RetrieveItem[T](ItemIdentifier itemId)
   at Umbraco.Courier.Core.GenericItemProvider`1.HandlePack(ItemIdentifier id)
   at Umbraco.Courier.Core.ItemProvider.Package(ItemIdentifier id)
   at Umbraco.Courier.RepositoryProviders.Local.Package(ItemIdentifier itemId)
   at Umbraco.Courier.RepositoryProviders.Local.Hash(ItemIdentifier itemId)
   at Umbraco.Courier.RepositoryProviders.Webservices.Repository.GetHashes(String sessionKey, ItemIdentifier[] itemIds)
   --- End of inner exception stack trace ---","StackTrace":"   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.EndInvoke(IAsyncResult asyncResult)\
   at Umbraco.Courier.RepositoryProviders.WebServiceProvider.RepositoryWebservice.EndGetHashes(IAsyncResult asyncResult)
   at Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider.GetHashes(ItemIdentifier[] itemIds)
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.GetTargetHashes(IPackagingTarget2 target, IEnumerable`1 ids)
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.PackageBatch()
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.Package()
   at Umbraco.Courier.Core.Tasks.PackagingTask.Run()
   at Umbraco.Courier.Core.BackgroundTaskRunner`1.ConsumeTaskInternal(T task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Courier.Core.TaskManager.GetSuccessfulProcessedTasks()
   at Umbraco.Courier.UI.Dialogs.CommitItem.GetTask(String id)","ExceptionType":"System.Web.Services.Protocols.SoapException"}
```

**Comment by nul800sebastiaan** [comment]
Hi @pyajamanam - if you have this problem in the latest version of Courier still then make sure to open an issue on the Courier issue tracker: https://github.com/umbraco/Umbraco.Courier.Issues
